from __future__ import annotations

import re
from dataclasses import dataclass
from datetime import datetime, timezone
from typing import Any

from fixops.db import IncidentSeverity, KnowledgeCategory


@dataclass
class ParsedLog:
    error_type: str
    affected_service: str | None
    key_terms: list[str]
    anomaly_signals: list[str]
    severity: IncidentSeverity
    start: datetime | None
    end: datetime | None


@dataclass
class CitedChunk:
    source_file: str
    chunk_index: int
    category: KnowledgeCategory | None
    content: str


class LocalLLMService:
    """Deterministic rule-based provider that uses the real knowledge base."""

    async def chat_complete(
        self,
        messages: list[Any],
        temperature: float = 0.2,
        max_tokens: int | None = None,
    ) -> str:
        del temperature, max_tokens
        user = " ".join(m.content for m in messages if getattr(m, "role", None) == "user")
        return (
            "Local analysis complete. This response was generated by the deterministic "
            f"local provider using the configured knowledge base. Prompt excerpt: {user[:160]}."
        )

    async def structured_complete(
        self,
        messages: list[Any],
        schema: type[Any],
        *,
        max_tokens: int | None = None,
    ) -> Any:
        del max_tokens
        prompt = "\n".join(getattr(m, "content", "") for m in messages)
        schema_name = schema.__name__
        if schema_name == "LogSignalsResponse":
            return self._build_log_analysis(prompt, schema)
        if schema_name == "RootCauseResponse":
            return self._build_root_cause(prompt, schema)
        if schema_name == "RemediationResponse":
            return self._build_remediation(prompt, schema)
        if schema_name == "ReportResponse":
            return self._build_report(prompt, schema)
        raise NotImplementedError(f"LocalLLMService does not support schema {schema_name}")

    def _extract_raw_log(self, prompt: str) -> str:
        if "Raw log:" not in prompt:
            return ""
        return prompt.split("Raw log:", 1)[1].split("\n\n", 1)[0].strip()

    def _extract_knowledge_context(self, prompt: str) -> list[CitedChunk]:
        chunks: list[CitedChunk] = []
        # Pattern: [CATEGORY] source_file#index
        #          content
        pattern = re.compile(
            r"^\[(?P<category>[^\]]+)\]\s+(?P<source_file>[^#\s]+)#(?P<index>\d+)\n(?P<content>(?:.*\n?)+?)(?=\n\[|\Z)",
            re.MULTILINE,
        )
        for match in pattern.finditer(prompt):
            cat = match.group("category").strip().upper()
            category = None
            for value in KnowledgeCategory:
                if value.value == cat:
                    category = value
                    break
            chunks.append(
                CitedChunk(
                    source_file=match.group("source_file"),
                    chunk_index=int(match.group("index")),
                    category=category,
                    content=match.group("content").strip(),
                )
            )
        return chunks

    def _extract_title(self, prompt: str) -> str | None:
        match = re.search(r"Incident title:\s*(.+)", prompt)
        return match.group(1).strip() if match else None

    def _parse_log(self, raw_log: str) -> ParsedLog:
        lowered = raw_log.lower()
        timestamps = [
            datetime.fromisoformat(value.replace("Z", "+00:00"))
            for value in re.findall(r"\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d+)?Z", raw_log)
        ]
        start = timestamps[0] if timestamps else None
        end = timestamps[-1] if timestamps else None

        service_match = re.search(r"(?:service|deployment|pod)\s+([a-z0-9_-]+)", lowered)
        affected_service = service_match.group(1) if service_match else None

        # Determine error type and severity from keyword patterns.
        error_type = "Application degradation"
        severity = IncidentSeverity.MEDIUM
        key_terms: list[str] = ["error spike", "latency increase"]
        anomaly_signals: list[str] = ["Repeated failures detected in raw logs"]

        if any(
            token in lowered for token in ("oom", "oomkilled", "out of memory", "exit code 137")
        ):
            error_type = "Container OOMKilled"
            severity = IncidentSeverity.HIGH
            key_terms = ["OOMKilled", "exit code 137", "memory limit"]
            anomaly_signals = ["Container terminated due to memory limit"]
        elif any(
            token in lowered
            for token in (
                "sqlstate 53300",
                "too many clients",
                "pool exhausted",
                "hikaripool",
                "connection is not available",
            )
        ):
            error_type = "Database connection pool exhaustion"
            severity = IncidentSeverity.HIGH
            key_terms = ["SQLSTATE 53300", "too many clients already", "HikariPool timeout"]
            anomaly_signals = [
                "Connection acquisition exceeded timeout",
                "Error rate spiked after saturation",
            ]
        elif any(token in lowered for token in ("redis", "connection refused", "redis timeout")):
            error_type = "Redis connection failure"
            severity = IncidentSeverity.HIGH
            key_terms = ["Redis", "connection refused", "timeout"]
            anomaly_signals = ["Cache dependency errors observed"]
        elif any(token in lowered for token in ("crashloop", "crashloopbackoff", "crash loop")):
            error_type = "Pod crashloop backoff"
            severity = IncidentSeverity.CRITICAL
            key_terms = ["CrashLoopBackOff", "pod restart"]
            anomaly_signals = ["Pod repeatedly failing readiness/liveness probes"]
        elif any(token in lowered for token in ("memory leak", "heap growing", "memory growing")):
            error_type = "Memory leak"
            severity = IncidentSeverity.HIGH
            key_terms = ["memory growth", "heap", "leak"]
            anomaly_signals = ["Memory usage trending upward without release"]
        elif any(token in lowered for token in ("cpu", "throttling", "cpu throttled")):
            error_type = "CPU throttling"
            severity = IncidentSeverity.MEDIUM
            key_terms = ["CPU", "throttling"]
            anomaly_signals = ["CPU quota exceeded"]
        elif any(token in lowered for token in ("network", "latency", "request timed out")):
            error_type = "Network latency / timeout"
            severity = IncidentSeverity.MEDIUM
            key_terms = ["latency", "timeout", "network"]
            anomaly_signals = ["Downstream response times elevated"]
        elif any(token in lowered for token in ("traffic spike", "rate limit", "429")):
            error_type = "Traffic spike / overload"
            severity = IncidentSeverity.HIGH
            key_terms = ["traffic surge", "rate limiting", "429"]
            anomaly_signals = ["Request rate exceeded capacity"]

        if severity == IncidentSeverity.MEDIUM and "error" in lowered:
            anomaly_signals.append("Error messages present in logs")

        return ParsedLog(
            error_type=error_type,
            affected_service=affected_service,
            key_terms=key_terms,
            anomaly_signals=anomaly_signals,
            severity=severity,
            start=start,
            end=end,
        )

    def _build_log_analysis(self, prompt: str, schema: type[Any]) -> Any:
        raw_log = self._extract_raw_log(prompt)
        parsed = self._parse_log(raw_log)
        return schema(
            error_type=parsed.error_type,
            affected_service=parsed.affected_service,
            key_terms=parsed.key_terms,
            anomaly_signals=parsed.anomaly_signals,
            timestamp_start=parsed.start,
            timestamp_end=parsed.end,
            severity_assessment=parsed.severity,
        )

    def _build_root_cause(self, prompt: str, schema: type[Any]) -> Any:
        raw_log = self._extract_raw_log(prompt)
        parsed = self._parse_log(raw_log)
        chunks = self._extract_knowledge_context(prompt)

        contributing: list[str] = []
        if parsed.severity in {IncidentSeverity.HIGH, IncidentSeverity.CRITICAL}:
            contributing.append("The failure pattern matches high-severity operational runbooks.")
        contributing.append("Correlated signals in the logs point to a single bottleneck.")

        # Use the highest-scored knowledge chunk to ground the answer.
        best = chunks[0] if chunks else None
        if best and best.category == KnowledgeCategory.POSTMORTEM:
            contributing.append("A prior postmortem describes the same symptom cluster.")

        evidence_refs: list[dict[str, Any]] = [
            {
                "source_type": "log",
                "source_ref": "incident_raw_log",
                "content": f"Observed {parsed.error_type.lower()} in the raw logs.",
                "relevance_score": 0.95,
            }
        ]
        for index, chunk in enumerate(chunks[:3], start=1):
            evidence_refs.append(
                {
                    "source_type": chunk.category.value.lower() if chunk.category else "knowledge",
                    "source_ref": f"{chunk.source_file}#{chunk.chunk_index}",
                    "content": chunk.content[:200] + ("..." if len(chunk.content) > 200 else ""),
                    "relevance_score": round(0.9 - index * 0.05, 2),
                }
            )

        confidence = 0.82
        if best:
            confidence = 0.9
        if parsed.severity == IncidentSeverity.MEDIUM:
            confidence = 0.75

        return schema(
            primary_cause=f"The incident is consistent with {parsed.error_type.lower()}.",
            contributing_factors=contributing,
            confidence_score=round(confidence, 2),
            reasoning_chain=(
                f"The log pattern for {parsed.error_type.lower()} matches the retrieved "
                f"{len(chunks)} knowledge chunk(s). The most relevant chunk is "
                f"{chunks[0].source_file if chunks else 'none'}#"
                f"{chunks[0].chunk_index if chunks else 0}."
            ),
            evidence_refs=evidence_refs,
        )

    def _build_remediation(self, prompt: str, schema: type[Any]) -> Any:
        chunks = self._extract_knowledge_context(prompt)
        raw_log = self._extract_raw_log(prompt)
        parsed = self._parse_log(raw_log)

        steps: list[dict[str, Any]] = []
        # Pull ordered remediation steps from playbook/runbook chunks when present.
        step_number = 1
        for chunk in chunks:
            if chunk.category not in {KnowledgeCategory.RUNBOOK, KnowledgeCategory.PLAYBOOK}:
                continue
            for line in chunk.content.splitlines():
                match = re.match(r"^\d+\.\s+(.+)", line.strip())
                if match and len(steps) < 4:
                    steps.append(
                        {
                            "order": step_number,
                            "action": match.group(1).strip(),
                            "rationale": f"From {chunk.source_file}#{chunk.chunk_index}",
                            "risk_level": "MEDIUM",
                            "command_hint": None,
                            "is_automated": False,
                        }
                    )
                    step_number += 1

        # Fallback generic steps if no actionable steps were extracted.
        if not steps:
            steps = [
                {
                    "order": 1,
                    "action": "Identify the scope of the incident and isolate affected workloads.",
                    "rationale": "Prevents further cascading failures.",
                    "risk_level": "LOW",
                    "command_hint": None,
                    "is_automated": False,
                },
                {
                    "order": 2,
                    "action": f"Investigate the primary symptom: {parsed.error_type}.",
                    "rationale": "Narrows the root cause quickly.",
                    "risk_level": "LOW",
                    "command_hint": None,
                    "is_automated": False,
                },
                {
                    "order": 3,
                    "action": "Apply the relevant runbook remediation steps and verify metrics.",
                    "rationale": "Use documented operational knowledge.",
                    "risk_level": "MEDIUM",
                    "command_hint": None,
                    "is_automated": False,
                },
            ]

        return schema(
            summary=(
                "A staged remediation plan based on the retrieved knowledge base and "
                "observed log signals."
            ),
            steps=steps,
        )

    def _build_report(self, prompt: str, schema: type[Any]) -> Any:
        raw_log = self._extract_raw_log(prompt)
        parsed = self._parse_log(raw_log)
        title = self._extract_title(prompt) or "Incident Investigation Report"
        chunks = self._extract_knowledge_context(prompt)

        now = datetime.now(timezone.utc)
        timeline: list[dict[str, Any]] = []
        if parsed.start:
            timeline.append(
                {
                    "timestamp": parsed.start.isoformat(),
                    "event": f"Incident began with {parsed.error_type.lower()} signals.",
                }
            )
        if parsed.end:
            timeline.append(
                {
                    "timestamp": parsed.end.isoformat(),
                    "event": "Latest observed failure in the supplied log window.",
                }
            )
        timeline.append(
            {
                "timestamp": now.isoformat(),
                "event": "Investigation report generated with grounded knowledge retrieval.",
            }
        )

        return schema(
            title=f"{title} - Investigation Report",
            executive_summary=(
                f"Investigation indicates {parsed.error_type.lower()}. "
                "The analysis used the local knowledge base and log signals to produce a "
                "root cause hypothesis and remediation plan."
            ),
            incident_summary=(
                f"The service experienced {parsed.error_type.lower()} during the incident window. "
                "Key signals include: " + ", ".join(parsed.anomaly_signals) + "."
            ),
            root_cause_section=(
                f"Primary cause: {parsed.error_type.lower()}. "
                "Contributing factors include correlated error signals and operational pressure."
            ),
            evidence_section=(
                "Evidence includes raw log signals and "
                f"{len(chunks)} knowledge chunk(s) retrieved from the runbook library."
            ),
            remediation_section=(
                "A staged remediation plan was produced from the retrieved runbooks and playbooks. "
                "Review each command hint and risk level before execution."
            ),
            timeline=timeline,
            format_version="1.0",
            generated_at=now,
        )
