"""initial schema"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'ae35b7919621'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incidents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('raw_log', sa.Text(), nullable=False),
    sa.Column('severity', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', name='incidentseverity', native_enum=False, length=20), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'INVESTIGATING', 'ANALYZED', 'RESOLVED', 'CLOSED', name='incidentstatus', native_enum=False, length=30), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('service_name', sa.String(length=100), nullable=True),
    sa.Column('environment', sa.String(length=50), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_chunks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_file', sa.String(length=255), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('RUNBOOK', 'PLAYBOOK', 'POSTMORTEM', name='knowledgecategory', native_enum=False, length=50), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('keywords', sa.JSON(), nullable=False),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_knowledge_category', 'knowledge_chunks', ['category'], unique=False)
    op.create_index('idx_knowledge_source', 'knowledge_chunks', ['source_file'], unique=False)
    op.create_table('investigations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('incident_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', name='investigationstatus', native_enum=False, length=30), nullable=False),
    sa.Column('current_step', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('root_cause_retried', sa.Boolean(), nullable=False),
    sa.Column('remediation_retried', sa.Boolean(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_investigations_incident_id', 'investigations', ['incident_id'], unique=False)
    op.create_index('idx_investigations_status', 'investigations', ['status'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('investigation_id', sa.Uuid(), nullable=False),
    sa.Column('incident_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('executive_summary', sa.Text(), nullable=False),
    sa.Column('incident_summary', sa.Text(), nullable=False),
    sa.Column('root_cause_section', sa.Text(), nullable=False),
    sa.Column('evidence_section', sa.Text(), nullable=False),
    sa.Column('remediation_section', sa.Text(), nullable=False),
    sa.Column('timeline', sa.JSON(), nullable=False),
    sa.Column('evidence_refs', sa.JSON(), nullable=False),
    sa.Column('remediation_steps', sa.JSON(), nullable=False),
    sa.Column('root_cause_retried', sa.Boolean(), nullable=False),
    sa.Column('remediation_retried', sa.Boolean(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('format_version', sa.String(length=10), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_reports_incident_id', 'reports', ['incident_id'], unique=False)
    op.create_index('idx_reports_investigation_id', 'reports', ['investigation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_reports_investigation_id', table_name='reports')
    op.drop_index('idx_reports_incident_id', table_name='reports')
    op.drop_table('reports')
    op.drop_index('idx_investigations_status', table_name='investigations')
    op.drop_index('idx_investigations_incident_id', table_name='investigations')
    op.drop_table('investigations')
    op.drop_index('idx_knowledge_source', table_name='knowledge_chunks')
    op.drop_index('idx_knowledge_category', table_name='knowledge_chunks')
    op.drop_table('knowledge_chunks')
    op.drop_table('incidents')
    # ### end Alembic commands ###
